### ISSUE TITLE
Tree.visit causes expetion..

### ISSUE THREAD

**Issue by jogibear9988** [mar10/wunderbaum#47]
I've this call:

         this._tree.visit((node) => {
              if (activeElements && activeElements.includes(node.data.ref)) {
                node.setSelected(true);
                node.setActive(true);
                node.makeVisible({ scrollIntoView: true });
              } else {
                node.setSelected(false);
                node.setActive(false);
              }
            });

wich causes this exception: (stacktrace may not match, it's my patched version)

        wunderbaum.esm.js:4562 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'update')
            at WunderbaumNode.update (wunderbaum.esm.js:4562:19)
            at WunderbaumNode.setActive (wunderbaum.esm.js:4481:62)
            at treeViewExtended.js:294:22
            at WunderbaumNode.visit (wunderbaum.esm.js:4921:19)
            at WunderbaumNode.visit (wunderbaum.esm.js:4928:35)
            at WunderbaumNode.visit (wunderbaum.esm.js:4928:35)
            at WbSystemRoot.visit (wunderbaum.esm.js:4928:35)
            at Wunderbaum.visit (wunderbaum.esm.js:7196:26)
            at TreeViewExtended._highlight (treeViewExtended.js:286:20)
            at TreeViewExtended.selectionChanged (treeViewExtended.js:262:14)

issue is here:

![image](https://github.com/mar10/wunderbaum/assets/364896/6de8c807-c0a9-45ef-b065-d95f748cf814)

Thias was also an issue before my changes...

**Comment by mar10** [comment]
This should be more performant, since it avoids many unneccessary updates. I assume it will also prevent the error.
```js
tree.runWithDeferredUpdate(() => {
  let lastActiveNode = null;
  this.visit((node) => {
    const flag = activeElements && activeElements.includes(node.data.ref);
    node.setSelected(flag);
    node.setActive(flag);
    if ( flag ) { lastActiveNode = node; }
  });
  if ( lastActiveNode ) {
    lastActiveNode.makeVisible({ scrollIntoView: true });
  }
});
```

**Comment by jogibear9988** [comment]
still the same issue:

this is my code:


     _highlight(activeElements) {
          this._tree.runWithDeferredUpdate(() => {
              let lastActiveNode = null;
              this._tree.visit((node) => {
                  const flag = activeElements && activeElements.includes(node.data.ref);
                  node.setSelected(flag);
                  node.setActive(flag);
                  if (flag) {
                      lastActiveNode = node;
                  }
              });
              if (lastActiveNode) {
                  lastActiveNode.makeVisible({ scrollIntoView: true });
              }
          });
      }


wunderbaum.esm.js:4583 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'update')
    at WunderbaumNode.update (wunderbaum.esm.js:4583:19)
    at WunderbaumNode.setActive (wunderbaum.esm.js:4495:62)
    at treeViewExtended.js:290:22
    at WunderbaumNode.visit (wunderbaum.esm.js:4942:19)
    at WunderbaumNode.visit (wunderbaum.esm.js:4949:35)
    at WunderbaumNode.visit (wunderbaum.esm.js:4949:35)
    at WbSystemRoot.visit (wunderbaum.esm.js:4949:35)
    at Wunderbaum.visit (wunderbaum.esm.js:7219:26)
    at treeViewExtended.js:287:24
    at Wunderbaum.runWithDeferredUpdate (wunderbaum.esm.js:6145:25)



<img width="949" alt="image" src="https://github.com/mar10/wunderbaum/assets/364896/2e4d5119-f1ad-43a5-8b35-2e5480982f53">

**Comment by jogibear9988** [comment]
The problem maybe is, I recreate the whole tree at some time:

      _recomputeTree(rootItem) {
          this._tree.root.removeChildren();
          this._getChildren(rootItem, null);
          this._tree.expandAll();
          this._filterNodes();
      }
      _getChildren(item, currentNode) {
          if (currentNode == null) {
              currentNode = this._tree.root;
          }
          const newNode = currentNode.addChildren({
              title: item.isRootItem ? '-root-' : item.nodeType === NodeType.Element ? item.name + " " + (item.id ? ('#' + item.id) : '') : '<small><small><small>#' + (item.nodeType === NodeType.TextNode ? 'text' : 'comment') + '&nbsp;</small></small></small> ' + DomConverter.normalizeContentValue(item.content),
              ref: item
          });
          for (let i of item.children()) {
              if (!i.isEmptyTextNode) {
                  this._getChildren(i, newNode);
              }
          }
      }

maybe the tree keeps track of some old tree items somewhere?

**Comment by jogibear9988** [comment]
this should show the issue: https://codesandbox.io/s/base-custom-webcomponent-forked-3q63dl

**Comment by jogibear9988** [comment]
or maybe the codesandbox is not yet the same issue, could try on a better reproduction

**Comment by jogibear9988** [comment]
okay, now with sleep...
https://codesandbox.io/s/base-custom-webcomponent-forked-3q63dl?file=/index.html
seems to be the same issue

**Comment by mar10** [comment]
Ok I correct my example: the setActive() should be removed from the loop, and simply get called once afterwards (it will call `makeVisible` by default).
It is an async method, so maybe that cause trouble when you rebuild the tree.


```js
tree.runWithDeferredUpdate(() => {
  let lastActiveNode = null;
  this.visit((node) => {
    const flag = activeElements && activeElements.includes(node.data.ref);
    node.setSelected(flag);
    if ( flag ) { lastActiveNode = node; }
  });
  if ( lastActiveNode ) {
    lastActiveNode.setActive(flag);
  }
});
```

BTW, there is also a `tree.selectAll()`, `tree.clear()`, `tree.addChildren()`, and `node.addChildren()` accepts an Array, ... so I guess your example was just a stripped down version of another implementation.

Please close if it works for you

**Comment by jogibear9988** [comment]
Also with your last code, I still got the error. But I removed now setActive completely, I don't need it
