### ISSUE TITLE
Error: Assertion failed

### ISSUE THREAD

**Issue by malishahi** [mar10/wunderbaum#6]
Trying to use Wunderbaum with React, but facing the following error. What errors could be related to this issues?

react_devtools_backend.js:4026 WbSystemRoot@__root__<'wb_1'> Error during load() (10) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] Error: Assertion failed.
    at assert (frontend.js:52255:916)
    at Wunderbaum._registerNode (frontend.js:52334:6187)
    at new WunderbaumNode (frontend.js:52316:1361)
    at WunderbaumNode.addChildren (frontend.js:52316:1850)
    at WunderbaumNode.addChildren (frontend.js:52316:1930)
    at WbSystemRoot.addChildren (frontend.js:52316:1930)
    at WbSystemRoot._loadSourceObject (frontend.js:52316:7302)
    at WbSystemRoot.load (frontend.js:52316:8313)
    at Wunderbaum.load (frontend.js:52334:20885)
    at new Wunderbaum (frontend.js:52334:3638) 
    at TreeTable (http://localhost:8443/client/frontend.js:13006:66)
    at Content (http://localhost:8443/client/frontend.js:13095:78)

**Comment by mar10** [comment]
Are you sending duplicate keys? If you need multiple nodes with identical keys ('clones'), you can pass `refKey` instead.
